version: "3"

services:
  db:
    image: mysql:5.7
    container_name: "dev_db"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
    #   timeout: 20s
    #   retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "dev_phpmyadmin"
    restart: always
    depends_on:
      - db
    ports:
      - 9090:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    # depends_on:
    #     mysql:
    #       condition: service_healthy
volumes:
  db_data: